# Copyright 2020 Drewry Pope
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: '3.8'
services:
  app:
    build:
      context: '.'
      args:
        VERSION: 'latest'
        LOGLEVEL: 'info'
        WORKDIR: '/usr/local/app'
        BUILD: 'build.sh'
        RELEASE:
    command: 'entrypoint.sh'
    image: 'app'
    restart: unless-stopped
    environment:
      TEXT: 'DEFAULT'
      MONGO_INITDB_DATABASE: 'MONGODB'
      MONGO_INITDB_USERNAME: 'MONGOUSER'
      MONGO_INITDB_PASSWORD:
      MONGO_HOSTNAME: 'mongo'
      MONGO_PORT: '27017'
      MONGO_DB: 'MONGODB'
    env_file:
      - .env
      - .env.mongo
      - .env.mongo.root
      - .env.twitter
    depends_on:
      - 'mongo'
    volumes:
      - './data:/usr/local/app/data'
    expose:
      - '27017-27019'
    networks:
      - 'backend'

  mongo:
    image: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: 'MONGODB'
      MONGO_INITDB_USERNAME: 'MONGOUSER'
      MONGO_INITDB_PASSWORD:
      MONGO_INITDB_ROOT_USERNAME: 'MONGOROOTUSER'
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - './mongo/init-mongo.js:/docker-netrypoint-initdb.d/init-mongo.js:ro'
      - './mongodata:/data/db'
    ports:
      - '27017-27019:27017-27019'
    expose:
      - '27017-27019'
    networks:
      - "backend"
networks:
  backend:

volumes:
  data:
